spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techrookie?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: chiyongs
    password: chiyongs

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
